"""Write ssx_datarefs.toml from scanner output, pruning candidates that split real functions.

Usage: python build_datarefs.py <missing.txt>... [--exclude <codegen_output.txt>]
A candidate is pruned when codegen reports an unresolved branch whose source lies in the
candidate's range and whose target lies before it (i.e. the candidate was a mid-function label).
"""
import re
import sys

args = sys.argv[1:]
excl_log = None
if '--exclude' in args:
    i = args.index('--exclude')
    excl_log = args[i + 1]
    del args[i:i + 2]

cands = set()
for path in args:
    for line in open(path):
        ref = int(re.search(r'first_ref=0x([0-9A-F]+)', line).group(1), 16)
        if 0x82288000 <= ref < 0x82289600:  # SEH scope tables point at in-function labels
            continue
        cands.add(int(line.split()[0], 16))

pruned = set()
try:
    pruned = {int(l, 16) for l in open('tools/pruned.txt').read().split()}
except FileNotFoundError:
    pass
if excl_log:
    registered = sorted(int(m, 16) for m in re.findall(
        r'SetFunction\(0x([0-9A-F]+)', open('generated/default/ssx_register.cpp').read()))
    import bisect
    for m in re.finditer(r'0x([0-9A-F]+) from 0x([0-9A-F]+)', open(excl_log).read()):
        tgt, src = int(m.group(1), 16), int(m.group(2), 16)
        # The candidate whose generated function contains the failing branch is a
        # mid-function label, not a real entry point.
        j = bisect.bisect_right(registered, src) - 1
        if j >= 0 and registered[j] in cands:
            pruned.add(registered[j])
    open('tools/pruned.txt', 'w').write('\n'.join(f'0x{a:08X}' for a in sorted(pruned)))
cands -= pruned

with open('ssx_datarefs.toml', 'w') as f:
    f.write('# Function entry points referenced only from data or lis/addi pairs (vtables, CRT\n'
            '# init tables, callbacks). Generated by tools/find_missing_funcs.py +\n'
            '# tools/build_datarefs.py; boundaries are discovered automatically.\n\n[functions]\n')
    for a in sorted(cands):
        f.write(f'0x{a:08X} = {{}}\n')
print(f'{len(cands)} functions written, {len(pruned)} pruned', file=sys.stderr)
